webapp:
  container_name: webapp
  restart: always
  dns: 8.8.8.8
  ports:
    - "8080:8080"
  build: webapp
  external_links:
    - eureka-server
    - config-server
    - logs
  environment:
      EUREKA_INSTANCE_HOSTNAME: webapp
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: true
      SPRING_CLOUD_CONFIG_DISCOVERY_SERVICEID: config-server
      SPRING_PROFILES_ACTIVE: default, syslog
